services:
    account_service:
        image: account_service
        build:
            context: ./services/account
        ports:
            - '8081:8080'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=yandex
            - POSTGRES_HOST=localhost
            - POSTGRES_PORT=5432

            - HTTP_SERVER_PORT=8080
        # depends_on:
        #     - db

    # document_service:
    #     image: document_service
    #     build:
    #         context: ./sevices/document
    #     ports:
    #         - '8082:8080'
    #     depends_on:
    #         - db

    # hospitals_service:
    #     image: hospitals_service
    #     build:
    #         context: ./sevices/hospitals
    #     ports:
    #         - '8083:8080'
    #     depends_on:
    #         - db

    # timetable_service:
    #     image: timetable_service
    #     build:
    #         context: ./services/timetable
    #     ports:
    #         - '8084:8080'
    #     depends_on:
    #         - db
#     db:
#         image: postgres:17
#         ports:
#             - '5432:5432'
#         environment:
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: password
#             POSTGRES_DB: mydatabase
# #     volumes:
# #       - postgres_data:/var/lib/postgresql/data # Подключение volume для сохранения данных
# # volumes:
# #   postgres_data:
